#version: '3.8'

#services:
 # strapi:
  #  image: strapi/strapi
   # environment:
    #  DATABASE_CLIENT: ${DATABASE_CLIENT}
     # DATABASE_HOST: ${DATABASE_HOST}
      #DATABASE_PORT: ${DATABASE_PORT}
      #DATABASE_NAME: ${DATABASE_NAME}
      #DATABASE_USERNAME: ${DATABASE_USERNAME}
      #DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      #DATABASE_SSL: ${DATABASE_SSL}
    #ports:
     # - "1337:1337"
    #depends_on:
     # - mysql
  #mysql:
   # image: mysql:8.4
    #environment:
     # MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      #MYSQL_DATABASE: ${MYSQL_DATABASE}
      #YSQL_USER: ${MYSQL_USER}
      #MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #ports:
     # - "3306:3306"
  #adminer:
   # image: adminer
    #restart: always
    #ports:
     # - 8080:8080
    #depends_on:
     # - mysql