#version: '3.8'

#services:
 # strapi:
  #  build: .
   # environment:
    #  HOST: ${HOST}
     # PORT: ${PORT}
      #APP_KEYS: ${APP_KEYS}
      #DATABASE_CLIENT: ${DATABASE_CLIENT}
      #DATABASE_HOST: ${DATABASE_HOST}
      #DATABASE_PORT: ${DATABASE_PORT}
      #DATABASE_NAME: ${DATABASE_NAME}
      #DATABASE_USERNAME: ${DATABASE_USERNAME}
      #DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      #DATABASE_SSL: ${DATABASE_SSL}
    #ports:
     # - "1337:1337"
    #depends_on:
     # - postgres:
      #    condition: service_healthy
    #command: sh -c "sleep 10 && yarn start"
  #postgres:
  #  image: postgres:15
   # environment:
    #  POSTGRES_DB: ${DATABASE_NAME}
     # POSTGRES_USER: ${DATABASE_USERNAME}
      #POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    #ports:
     # - "5432:5432"
    #healthcheck:
     # test: ["CMD", "pg_isready", "-U", "${DATABASE_USERNAME}"]
      #interval: 10s
      #timeout: 5s
      #retries: 5
  #adminer:
   # image: adminer
    #restart: always
    #ports:
     # - 8080:8080
    #depends_on:
     # - postgres